SIE/urls.py
from django.contrib import admin
from django.urls import path, include

# 站点主页 
from django.shortcuts import render
def home(request):
    return render(request,'home.html')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('exam/', include('exam.urls')),
    path('',home,name='home'),
    path('lx/', include('lx.urls')),
]

exam/urls.py
from django.urls import path
from . import views

app_name = 'exam'
urlpatterns = [
    path('', views.index, name='index'),
    path('loginStudent/', views.loginStudent, name='loginStudent'),
    path('loginTeacher/', views.loginTeacher, name='loginTeacher'),
    # path('studentLogin/', views.studentLogin, name='studentLogin'),
    path('showGrade',views.showGrade),
    path('queryStudent/',views.queryStudent),
    path('startExam/',views.startExam),
    path('calGrade/',views.calGrade),
]

lx/urls.py
from django.urls import path
from .views import ArticleDetailView

urlpatterns = [
    path('', ArticleDetailView.as_view(), name='article-detail'),
]

exam/models.py
from django.db import models

GENDER = (('male','女'),('female','男'))
DEPT = (('信息工程学院','信息工程学院'),)
MAJOR =(
    ('计算机网络技术','计算机网络技术'),
    ('计算机应用技术','计算机应用技术'),
    ('软件技术','软件技术'),
    ('云计算技术与应用','云计算技术与应用'),
    ('大数据技术与应用','大数据技术与应用'),
    ('网络安全与管理','网络安全与管理'),
    ('电子信息工程技术','电子信息工程技术'),
    )
# CLASS=(('2019','2019'),('2020','2020'),('2021','2021'),)
# Freshman, sophomore, Junior

SUBJECT =(
    ('Python','Python程序设计'),
    ('C','C语言程序设计'))

class Student(models.Model):
    id=models.CharField('学号',max_length=32,primary_key=True)
    name=models.CharField('姓名',max_length=32)
    password=models.CharField('密码',max_length=32,default='123456')
    gender=models.CharField('性别',max_length=32,choices=GENDER,default='男')
    dept=models.CharField('学院',max_length=32,choices=DEPT,default='信息工程学院')
    major=models.CharField('专业',max_length=32,choices=MAJOR,default='计算机网络技术')
    # Class=models.CharField('班级',max_length=32,choices=CLASS),
    email=models.EmailField('邮箱',unique=True)
    birth=models.DateField('出生日期')
    telephone = models.CharField('电话', max_length=32)            

    class Meta:
        db_table='student'
        verbose_name='学生'
        verbose_name_plural=verbose_name

    def __str__(self):
        return self.id

class Teacher(models.Model):
    id=models.CharField("教工号",max_length=32,primary_key=True)
    name=models.CharField('姓名',max_length=32)
    password=models.CharField('密码',max_length=32,default='123456')
    gender=models.CharField('性别',max_length=32,choices=GENDER,default='男')
    dept=models.CharField('学院',max_length=32,choices=DEPT,default='信息工程学院')
    email=models.EmailField('邮箱',default=None)
    birth=models.DateField('出生日期')
    telephone = models.CharField('电话', max_length=32)

    class Meta:
        db_table='teacher'
        verbose_name='教师'
        verbose_name_plural=verbose_name

    def __str__(self):
        return self.name

class Question(models.Model):
    ANSWER=(
        ('A','A'),
        ('B','B'),
        ('C','C'),
        ('D','D'),
    )
    LEVEL={
        ('1','easy'),
        ('2','general'),
        ('3','difficult'),
    }
    id = models.AutoField(primary_key=True)
    subject = models.CharField('科目',choices=SUBJECT, max_length=32,default='Python')
    title = models.TextField('题目')
    optionA=models.CharField('A选项',max_length=50)
    optionB=models.CharField('B选项',max_length=50)
    optionC=models.CharField('C选项',max_length=50)
    optionD=models.CharField('D选项',max_length=50)
    answer=models.CharField('答案',max_length=32,choices=ANSWER)
    level=models.CharField('等级',max_length=32,choices=LEVEL,default='1')
    score=models.IntegerField('分数',default=1)

    class Meta:
        db_table='question'
        verbose_name='单项选择题'
        verbose_name_plural=verbose_name

    def __str__(self):
        return '<%s:%s>'%(self.subject,self.title);

class Paper(models.Model):
    id = models.AutoField(primary_key=True)
    #题号qid 和题库为多对多的关系
    qid=models.ManyToManyField(Question)
    tid=models.ForeignKey(Teacher,on_delete=models.CASCADE)
    subject=models.CharField('科目',choices=SUBJECT,max_length=20,default='python')
    major=models.CharField('考卷适用专业',choices=MAJOR,max_length=32)
    examtime=models.DateTimeField() 

    class Meta:
        db_table='paper'
        verbose_name='试卷'
        verbose_name_plural=verbose_name
    def __str__(self):
        return self.major

# Class schedule 课表 太复杂没做成
class Schedule(models.Model):
    tid=models.ManyToManyField(Teacher)
    dept=models.CharField('学院',max_length=32,choices=DEPT,default='信息工程学院')
    major=models.CharField('专业',choices=MAJOR,max_length=32,default='计算机网络技术')
    Class=models.CharField('班级',max_length=32)
    subject=models.CharField('科目',choices=SUBJECT,max_length=20,default='python')


class Grade(models.Model):
    sid=models.ForeignKey(Student,on_delete=models.CASCADE,default='')
    subject=models.CharField('科目',choices=SUBJECT,max_length=32,default='python')
    grade=models.IntegerField()

    def __str__(self):
        return '<%s:%s>'%(self.sid,self.grade);

    class Meta:
        db_table='grade'
        verbose_name='成绩'
        verbose_name_plural=verbose_name

exam/forms.py
from django import forms

class StudentForm(forms.Form):
    sn = forms.CharField(label="学号", max_length=128, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': "Student number",'autofocus': ''}))
    password = forms.CharField(label="密码", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control','placeholder': "Password"}))

class TeacherForm(forms.Form):
    sn = forms.CharField(label="教工号", max_length=128, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': "Faculty number",'autofocus': ''}))
    password = forms.CharField(label="密码", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control','placeholder': "Password"}))

class RegisterForm(forms.Form):
   
    gender = (
        ('male', "男"),
        ('female', "女"),
    )

    DEPT = (('信息工程学院','信息工程学院'),)
    MAJOR =(
        ('计算机网络技术','计算机网络技术'),
        ('计算机应用技术','计算机应用技术'),
        ('软件技术','软件技术'),
        ('云计算技术与应用','云计算技术与应用'),
        ('大数据技术与应用','大数据技术与应用'),
        ('网络安全与管理','网络安全与管理'),
        ('电子信息工程技术','电子信息工程技术'),
        )

    id = forms.CharField(label="学号", max_length=32, widget=forms.TextInput(attrs={'class': 'form-control'}))
    username = forms.CharField(label="用户名", max_length=128, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label="密码", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label="确认密码", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label="邮箱地址", widget=forms.EmailInput(attrs={'class': 'form-control'}))
    sex = forms.ChoiceField(label='性别', choices=gender)
    dept = forms.ChoiceField(label='学院', choices=DEPT)
    major = forms.ChoiceField(label='专业', choices=MAJOR)
    sex = forms.ChoiceField(label='性别', choices=gender)
    birth =forms.DateField(label='出生日期')
    telephone = forms.CharField(label='电话')
               

          
    
   

exam/views.py
from django.shortcuts import render,redirect
from django import forms
from django.http import HttpResponse
from django.contrib.auth import logout
from .models import Student,Teacher,Paper,Question,Grade
from .forms import StudentForm,TeacherForm,RegisterForm

def index(request):
    return render(request,'exam/index.html')

def logout(request):
    return redirect('/exam')

def register(request):
    if request.session.get('is_login', None):
        return redirect('/exam/')

    if request.method == 'POST':
        register_form = RegisterForm(request.POST)
        message = "请检查填写的内容！"
        if register_form.is_valid():
            id = register_form.cleaned_data.get('id')
            username = register_form.cleaned_data.get('username')
            password1 = register_form.cleaned_data.get('password1')
            password2 = register_form.cleaned_data.get('password2')
            email = register_form.cleaned_data.get('email')
            sex = register_form.cleaned_data.get('sex')
            dept = register_form.cleaned_data.get('dept')
            major = register_form.cleaned_data.get('major')
            birth = register_form.cleaned_data.get('birth')
            telephone = register_form.cleaned_data.get('telephone')

            if password1 != password2:
                message = '两次输入的密码不同！'                
            else:
                same_name_user = Student.objects.filter(id=id)
                if same_name_user:
                    message = '学生已经存在'
                else:
                    same_email_user = Student.objects.filter(email=email)
                    if same_email_user:
                        message = '该邮箱已经被注册了！'
                    
                    else:

                        new_user = Student()
                        new_user.id=id
                        new_user.name = username
                        new_user.password = password1
                        new_user.email = email
                        new_user.sex = sex
                        new_user.dept = dept
                        new_user.major = major
                        new_user.birth = birth
                        new_user.telephone = telephone
                        new_user.save()

                        return redirect('/exam/')

    register_form = RegisterForm()
    return render(request, 'exam/register.html', locals())

def loginStudent(request):
    if request.method == 'POST':
        login_form = StudentForm(request.POST)
        message = '请检查填写的内容！'
        if login_form.is_valid():
            sn = login_form.cleaned_data.get('sn')
            password = login_form.cleaned_data.get('password')

            try:
                student = Student.objects.get(id=sn)
                print(sn,student.id)
            except :
                message = '学生不存在！'                

            else:
                if student.password == password:
                    #查询考试信息 学生所在专业的所有试卷
                    paper=Paper.objects.filter(major=student.major)
                    
                    #查询成绩信息
                    grade=Grade.objects.filter(sid=student.id)
                    context = {'student':student,'paper':paper,'grade':grade}
                    return render(request,'exam/studentLogin.html', context=context)
                else:
                    message = '密码不正确！'              

    login_form = StudentForm()
    return render(request, 'exam/loginStudent.html', locals())


def loginTeacher(request):
    if request.method == 'POST':
        login_form = TeacherForm(request.POST)
        message = '请检查填写的内容！'
        if login_form.is_valid():
            sn = login_form.cleaned_data.get('sn')
            password = login_form.cleaned_data.get('password')

            try:
                teacher = Teacher.objects.get(id=sn)
                if teacher.password == password:
                    # 实现成绩统计功能
                    #在试卷表 paper 找到该老师发布的试题
                    paper=Paper.objects.filter(tid=teacher.id)

                    data1=Grade.objects.filter(subject='python',grade__lt=60).count()
                    data2=Grade.objects.filter(subject='python',grade__gte=60,grade__lt=70).count()
                    data3=Grade.objects.filter(subject='python', grade__gte=70, grade__lt=80).count()
                    data4=Grade.objects.filter(subject='python', grade__gte=80, grade__lt=90).count()
                    data5=Grade.objects.filter(subject='python', grade__gte=90).count()

                    data6 = Grade.objects.filter(subject='数据库原理', grade__lt=60).count()
                    data7= Grade.objects.filter(subject='数据库原理', grade__gte=60, grade__lt=70).count()
                    data8= Grade.objects.filter(subject='数据库原理', grade__gte=70, grade__lt=80).count()
                    data9 = Grade.objects.filter(subject='数据库原理', grade__gte=80, grade__lt=90).count()
                    data10= Grade.objects.filter(subject='数据库原理', grade__gte=90).count()


                    data_1={'data1':data1,'data2':data2,'data3':data3,'data4':data4,'data5':data5}
                    data_2 = {'data6': data6, 'data7': data7, 'data8': data8, 'data9': data9, 'data10': data10}

                    context = {'teacher':teacher,'paper':paper,'data_1':data_1,'data_2':data_2}
                    return render(request,'exam/teacherLogin.html', context=context)
                
                message = '密码不正确！' 
            except :
                message = '教师不存在！'                

    login_form = TeacherForm()
    return render(request, 'exam/loginTeacher.html', locals())

#教师查看成绩
def showGrade(request):
    subject1=request.GET.get('subject')
    grade=Grade.objects.filter(subject=subject1)

    data1 = Grade.objects.filter(subject=subject1, grade__lt=60).count()
    data2 = Grade.objects.filter(subject=subject1, grade__gte=60, grade__lt=70).count()
    data3 = Grade.objects.filter(subject=subject1, grade__gte=70, grade__lt=80).count()
    data4 = Grade.objects.filter(subject=subject1, grade__gte=80, grade__lt=90).count()
    data5 = Grade.objects.filter(subject=subject1, grade__gte=90).count()

    data = {'data1': data1, 'data2': data2, 'data3': data3, 'data4': data4, 'data5': data5}

    return render(request,'showGrade.html',{'grade':grade,'data':data,'subject':subject1})

#教师按条件查询学生
def queryStudent(request):
    #获取教师查询的条件值
    sid=request.GET.get('id')
    sex=request.GET.get('sex')
    subject=request.GET.get('subject')

    #获取老师的id
    tid=request.GET.get('tid')
    teacher = Teacher.objects.get(id=tid)
    paper = Paper.objects.filter(tid=teacher.id)

    # print(sid,sex,subject)
    from django.db import connection,transaction
    cursor=connection.cursor()
    sql="select * from grade,student where student.id=grade.sid_id " \
        "and student.id like %s and grade.subject like %s and student.sex like %s and '1'='1'"
    val=('%'+sid+'%','%'+subject+'%','%'+sex+'%')
    cursor.execute(sql,val)
    result=dictfetchall(cursor)


    # print(result)
    return render(request,'teacher.html',{'teacher':teacher,'result':result,'paper':paper})

#将使用原生sql语句查到的结果由tuple类型转换为dictionary(字典)类型
def dictfetchall(cursor):
    "将游标返回的结果保存到一个字典对象中"
    desc = cursor.description
    return [
    dict(zip([col[0] for col in desc], row))
    for row in cursor.fetchall()
    ]


#学生考试 的视图函数
def startExam(request):
    sid = request.GET.get('sid')
    pid = request.GET.get('pid')

    student=Student.objects.get(id=sid)
    # 当前试卷
    # paper=Paper.objects.filter(id=pid)
    paper=Paper.objects.get(id=pid)
    # 学生和考试试卷 exam.html
    return render(request,'exam/exam.html',{'student':student,'paper':paper})


#计算由exam.html模版传过来的数据计算成绩
def calGrade(request):

    if request.method=='POST':
        # 学号和试卷号
        sid=request.POST.get('sid')
        pid = request.POST.get('pid')

        # 重新生成Student实例，Paper实例，Grade实例，名字和index中for的一致，可重复渲染
        student= Student.objects.get(id=sid)
        # 当前测试试卷
        paper = Paper.objects.get(id=pid)
        # grade = Grade.objects.filter(sid=student.id)

        # 计算该门考试的学生成绩 
        question= paper.qid.values('id','answer','score')

        score=0   # 初始化一个成绩为0
        for q in question:
            qid=str(q['id'])            # int 转 string,通过qid找到题号
            ans=request.POST.get(qid) # 通过 qid 得到学生关于该题的作答  

            if ans==q['answer']:#判断学生作答与正确答案是否一致
                score+=q['score']#若一致,得到该题的分数,累加score变量

        #向Grade表中插入数据
        Grade.objects.create(sid_id=sid,subject=paper.subject,grade=score)
        grade = Grade.objects.filter(sid=student.id)
        # 有关该生的所有试卷
        paper=Paper.objects.filter(major=student.major)
        # 重新渲染studentLogin.html模板
        return render(request,'exam/studentLogin.html',{'student':student,'paper':paper,'grade':grade})

exam/templates/exam/index-1.html
{% extends "base.html" %}
{% block title %}考试系统{% endblock %}
{% block nav %} 
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="#">导航栏</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarToggler">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="/">主页 <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#tsModal" data-toggle="modal" data-ts="教师登录" data-sn='职工号'>教师登录</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#tsModal" data-toggle="modal" data-ts="学生登录" data-sn="学号">学生登录</a>
      </li>
    </ul>
  </div>
</nav> 

{% endblock %}

{% block main %}
<hr>
<h2>当前页面考试系统</h2>
<hr>
<h3>考试说明</h3>
<textarea name="" id="" cols="100" rows="20">
    全国各地方每年在高考前都会发布最新的《高考考试说明》，《高考考试说明》是高考命题的主要参考依据，它从试卷结构、考试内容和要求等多个方面对高考试题做出了规范，对于各位参加高考的考生而言，多花点时间了解考试说明是一件十分必要的事情。  

    学习 Web 开发 网站：
    https://developer.mozilla.org/zh-CN/

</textarea>

<hr>
{% comment %} style=“width:200px;height:320px”  {% endcomment %}

<div class="modal fade text-left" id="tsModal" tabindex="-1" role="dialog" aria-labelledby="tsModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="tsModalLabel">登录</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {% comment %} <form class="form-login" action="{% url 'exam:loginStudent' %}" method="post"> {% endcomment %}
        <form class="form-login" method="post" action="/exam/login/">
          {% csrf_token %}
          <div class="form-group">
            <label for="ts-id" class="modal-label col-form-label">职工号</label>
            <input type="text" class="form-control" id="ts-id" name="tsid">
          </div>
          <div class="form-group">
            <label for="ts-passpord" class="col-form-label">密码</label>
            <input type="text" class="form-control" id="ts-passpord" name='tspassword'>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="submit"" class="btn btn-primary">确定</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">取消</button>
      </div>
    </div>
  </div>
</div>



{% endblock %}

{% block script %}
<script type="text/javascript">
  $('#tsModal').on('show.bs.modal', function (event) {
    var button = $(event.relatedTarget) 
    var ts = button.data('ts')     
    var sn = button.data('sn')
    var modal = $(this)
    modal.find('.modal-title').text(ts)
    modal.find('.modal-label').text(sn)
  })
</script>
{% endblock %}

exam/templates/exam/index.html
{% extends "base.html" %}
{% block title %}考试系统{% endblock %}
{% block nav %} 
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="#">导航栏</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarToggler">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="/">首页<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/exam/loginTeacher/">教师登录</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/exam/loginStudent/">学生登录</a>
      </li>
    </ul>
  </div>
</nav> 

{% endblock %}

{% block main %}

<div class="tab-content" id="pills-tabContent">
  <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
    <hr>
    <h2>当前页面考试系统</h2>
    <hr>
    <h3>考试说明</h3>
    <textarea name="" id="" cols="100" rows="20">
        全国各地方每年在高考前都会发布最新的《高考考试说明》，《高考考试说明》是高考命题的主要参考依据，它从试卷结构、考试内容和要求等多个方面对高考试题做出了规范，对于各位参加高考的考生而言，多花点时间了解考试说明是一件十分必要的事情。  

        学习 Web 开发 网站：
        https://developer.mozilla.org/zh-CN/

    </textarea>

    <hr>
  
  </div>
</div>
{% endblock %}

exam/templates/exam/loginStudent.html
{% extends "exam/index.html" %}
{% block main %}
<div class="container text-left" style="width: 420px; height: 300px; padding: 50px;">
  <form class="form-login" action="{% url 'exam:loginStudent' %}" method="post">
    {% csrf_token %}

    <h3 class="text-center">欢迎登录</h3>
    <div class="form-group">
      <label for="inputSN">学号</label>
      <input type="text" class="form-control" id="inputSN" name="sn">     
    </div>

    <div class="form-group">
      <label for="inputPassword">密码</label>
      <input type="password" class="form-control" id="inputPassword" name="password">
    </div>
    
    <a href="/exam/register/" class="text-success " ><ins>学生注册</ins></a>
    <button type="submit" class="btn btn-primary float-right">确认</button>
    
    {% if message %}
    <div class="alert alert-warning" role="alert" style="margin: 20px;">{{ message }}</div>
    {% endif %}
  </form>
</div>

{% endblock %}

exam/templates/exam/loginTeacher.html
{% extends "exam/index.html" %}
{% block main %}
<div class="container text-left" style="width: 420px; height: 300px; padding: 50px;">
  <form class="form-login" action="{% url 'exam:loginTeacher' %}" method="post">
    {% csrf_token %}

    <h3 class="text-center">欢迎登录</h3>
    <div class="form-group">
      <label for="inputSN">教工号</label>
      <input type="text" class="form-control" id="inputSN" name="sn">     
    </div>

    <div class="form-group">
      <label for="inputPassword">密码</label>
      <input type="password" class="form-control" id="inputPassword" name="password">
    </div>
    
    <a href="/exam/register/" class="text-success " ><ins>教师注册</ins></a>
    <button type="submit" class="btn btn-primary float-right">确认</button>
    
    {% if message %}
    <div class="alert alert-warning" role="alert" style="margin: 20px;">{{ message }}</div>
    {% endif %}
  </form>
</div>

{% endblock %}

exam/templates/exam/studentLogin.html
{% extends "base.html" %}
{% block nav %} 
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="#">导航栏</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarToggler">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home' %}">首页<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'exam:index' %}">在线考试<span class="sr-only">(current)</span></a>
      </li>
  </div>
</nav> 

{% endblock %}
{% block main %}

<div class="container mx-auto ">
  <div class="float-left m-5 p-3 border">
    <H3>个人信息</H3>
    <table class="table">
      <thead>
        <tr class="table-active">
          <th>属性</th>
          <th>信息</th>  
        </tr>
      </thead>
      <tbody class=" text-left">
        <tr>
          <td>学号</td>
          <td>{{ student.id }}</td>  
        </tr>
        <tr class="table-active">
          <td>姓名</td>
          <td>{{ student.name }}</td>  
        </tr>
        <tr>
          <td>性别</td>
          <td>{{ student.gender }}</td>  
        </tr>
        <tr class="table-active">
          <td>学院</td>
          <td>{{ student.dept }}</td>  
        </tr>  
         <tr>
          <td>专业</td>
          <td>{{ student.major }}</td>  
        </tr>  
        <tr class="table-active">
          <td>邮箱地址</td>
          <td>{{ student.email }}</td>  
        </tr>
        <tr>
          <td>出生日期</td>
          <td>{{ student.birth }}</td>  
        </tr>  
        <tr class="table-active">
          <td>电话</td>
          <td>{{ student.telephone }}</td>  
        </tr>
      </tbody>
    </table>
  </div>  

  <div class="float-left border p-3 mt-5">
    <h3>考试信息</h3>    
    <table class="table">
      <thead>
        <tr>
          <th>考试科目</th>
          <th>考试时间</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
      <!-- 有关该生的所有试卷 -->
      {% for p in paper %}
      <tr class="table-info">
        <td>{{ p.subject }}</td>
        <td>{{ p.examtime }}</td>
        <td>
          <!-- 学号和试卷号 startExam视图 -->
          <a href="/exam/startExam/?sid={{ student.id }}&pid={{ p.id }}">
            <button class="btn btn-primary" id="toExam+{{ p.subject }}">开始考试</button>
          </a>
        </td>
      </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
    
  <div class="float-left border p-3 m-5">
    <h3>考试成绩</h3>

    <table class="table">
      <thead>
        <tr>

          <th>科目</th>
          <th>成绩</th>
        </tr>
      </thead>
    <tbody>
    {% for grade1 in grade %}
      <tr class="table-primary">

        <td>{{ grade1.subject }}</td>
        <td>{{ grade1.grade }}</td>
      </tr>
    {% endfor %}  
    </tbody>
  </table>
  </div>
</div>

<div style="clear: both;"></div>

{% endblock %}

exam/templates/exam/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>测试成绩页</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="../static/bootstrap-4.3.1-dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- 必须在引入bootstarp.js之前引入 -->
    <script src="../static/jquery-3.3.1.min.js"></script>

    <script src="../static/bootstrap-4.3.1-dist/js/bootstrap.min.js"></script>

</head>
<body>
<div class="container">
    <table class="table">
        <thead>
          <tr>
              <th>学号</th>
            <th>姓名</th>
              <th>专业</th>
            <th>科目</th>
            <th>成绩</th>
          </tr>
        </thead>
    <tbody>

    {% for result1 in result %}
    <tr class="table-primary">
        <td>{{ result1.id }}</td>
        <td>{{ result1.name }}</td>
        <td>{{ result1.major }}</td>
        <td>{{ result1.subject }}</td>
        <td>{{ result1.grade }}</td>


{#        <td>#}
{#            {% for grade1 in result1.grade_set.all %}#}
{##}
{#                <span>{{ grade1.grade }}</span>#}
{##}
{##}
{#            {% endfor %}#}
{#        </td>#}

    </tr>
    {% endfor %}
    </tbody>
  </table>
</div>

</body>
</html>